baseURL = 'https://XBlankZGap.github.io/seo-portfolio/'
languageCode = 'en-us'
title = "Sophy's SEO Portfolio"
theme = 'PaperMod'
defaultTheme = 'dark'

[[menu.main]]
    name = "About Me"
    url = "about/"
    weight = 40

[[menu.main]]
    name = "Contact"
    url = "contact/"
    weight = 60

[markup.goldmark.renderer]
    unsafe = true

[params]
    ShowReadingTime = true
    ShowBreadCrumbs = true
    ShowPostNavLinks = true

[outputs]
    home = ["HTML", "RSS", "JSON"]

